CollegeManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('admission/', include('admission.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/', include('student.urls')),
    path('address/', include('address.urls')),
    path('employmentHistory/', include('empoymentHistory.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('faculty/', include('faculty.urls')),
    path('department/', include('department.urls')),
    path('institution/', include('INSTITUTION.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('system/', include('system.urls')),
    path('course/', include('course.urls')),
    path('lecturer/', include('lecture.urls')),
    path('klassrm/', include('classRoom.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from .views import LandingPage, AboutUsPage, INSTITUTION_NAME, LoginPage, LogoutPage, AdministratorHomePage
from django.urls import path

app_name = 'Home'
urlpatterns = [
    path('', LandingPage.as_view(), name='landing_page'),
    path('about'+INSTITUTION_NAME.get('institution_short_name').lower(), AboutUsPage.as_view(), name="about_institution"),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('administration/', AdministratorHomePage.as_view(), name='admin'),
]

course/urls.py
from django.urls import path, include
from .views import (
    CourseCreationView,
    CourseDetailView,
    StudentCourseListView,
    get_students_other_courses,
    StaffCourseListView,
    StudentCourseDetail,
    LecturerCoursesListView,
    CourseAssignmentCreateView,
    CourseAssigmentUpdateView,
    get_lecturer_short_infor,
    remove_lecturer_from_course_history,
    LecturerCourseDetailView,
    get_course_details,
)

app_name = 'Course'

staff_urlpatterns = [
    path('all/', StaffCourseListView.as_view(), name='staff_all'),
]

course_assignment_urlpatterns = [
    path('toanotherlecturer/<str:course_code>/', CourseAssignmentCreateView.as_view(), name='assign2another'),
    path('updateassigment/<int:courseassignmentpk>/', CourseAssigmentUpdateView.as_view(), name='assign_update'),
    path('getlecturershrtinfo/<slug:user_slug>/<int:assignment_id>/', get_lecturer_short_infor, name='rm_lec_short_info'),
    path('rmelecturer4rmcoursehist/<str:course_code>/<int:course_assignment_id>/', remove_lecturer_from_course_history, name='assignment_rm_lec4rmhist')

]

student_urlpatterns = [
    path('othersc/', get_students_other_courses, name='student_viewmore'),
    path('thissemester/', StudentCourseListView.as_view(), name='student_current'),
    path('details/<course_code>/', StudentCourseDetail.as_view(), name='stu_details'),
]

lecturer_urlpatterns = [
    path('list/', LecturerCoursesListView.as_view(), name='lec_list'),
    path('details/<course_code>/', LecturerCourseDetailView.as_view(), name='lec_detail'),
]
api_urlpatterns = [
    path('<str:course_code>/details/', get_course_details, name='lec_detail_ajax'),
]
urlpatterns = [
    path('staff/', include(api_urlpatterns)),
    path('api/', include(staff_urlpatterns)),
    path('lecturer/', include(lecturer_urlpatterns)),
    path('addnew/', CourseCreationView.as_view(), name='create'),
    path('detail/<str:code>/<int:id>/', CourseDetailView.as_view(), name='detail'),
    path('student/', include(student_urlpatterns)),
    path('courseassignment/', include(course_assignment_urlpatterns)),
]

course/forms.py
from django import forms
from .models import Course, CourseAssignment
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import FormActions, StrictButton, UneditableField
from crispy_forms.layout import Div


class DFlexDiv(Div):
    def __init__(self, *args, **kwargs):
        super(DFlexDiv, self).__init__(*args, **kwargs)


def form_helper(self):
    helper = FormHelper(self)
    helper.layout.append(
        FormActions(
            StrictButton('Reset', type='reset', css_class='btn-light shadow-sm'),
            StrictButton('Save', type='submit', css_class='btn-primary shadow-sm', onclick='dynamicSpinner(this)'),
            css_class='d-flex justify-content-end',
        )
    )
    return helper


class CourseCreationForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('name', 'code', 'programme', 'semester', 'level', 'credit_hours', 'level', 'description')

    @property
    def helper(self):
        helper = form_helper(self)
        helper[:2].wrap_together(DFlexDiv, css_class='d-flex  gap-3', css_id='IDnameCode')
        return helper


class CourseFilter(forms.Form):
    name_start_with = forms.CharField(max_length=10, required=False)
    name = forms.CharField(max_length=10, required=False, help_text='Search by course name')
    course_code = forms.CharField(max_length=20, required=False,
                                  help_text='Course Code contains or similar.')
    programme_name = forms.CharField(required=False,
                                     help_text='Programme name like or contains. Search by programme name.')
    paginate_by = forms.CharField(required=False, help_text='Limit page number to.', widget=forms.NumberInput)

    @property
    def helper(self):
        helper = form_helper(self)
        helper[:2].wrap_together(DFlexDiv, css_class='d-flex  gap-3', css_id='IDnameCode')
        return helper


class CourseAssignmentForm(forms.ModelForm):
    class Meta:
        model = CourseAssignment
        fields = ('course', 'lecturer', 'is_tutor')

    @property
    def helper(self):
        helper = form_helper(self)
        helper[0].wrap_once(DFlexDiv, css_class='user-select-none')
        return helper

course/views.py
from django.shortcuts import get_object_or_404, reverse
from django.http import Http404
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from .models import Course, Programme, models, CourseAssignment

from .forms import (
    CourseCreationForm,
    CourseFilter,
    CourseAssignmentForm,
)
from system.models import SemesterAcademicYearModel
from INSTITUTION.utils import get_back_url, get_next_url
from django.http.response import JsonResponse


class CourseCreationView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Course
    form_class = CourseCreationForm
    permission_required = 'course.add_course'
    template_name = 'course/staff/create.html'

    def get_context_data(self, **kwargs):
        ctx = super(CourseCreationView, self).get_context_data(**kwargs)
        ctx['title'] = 'Add Course'
        ctx['header'] = 'New Course'
        try:
            ctx['topheader'] = Programme.objects.get(id=self.request.GET.get('prg'))
        except Programme.DoesNotExist:
            pass
        ctx['back_url'] = self.request.GET.get('back')
        return ctx

    def get_initial(self):
        initial = super(CourseCreationView, self).get_initial()
        initial['programme'] = self.request.GET.get('prg')
        return initial

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(CourseCreationView, self).form_valid(form)


class CourseDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    permission_required = 'course.view_course'
    template_name = 'course/staff/detail.html'
    model = Course

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, code=self.kwargs['code'], id=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        ctx = super(CourseDetailView, self).get_context_data(**kwargs)
        ctx['title'] = '%s' % self.object
        ctx['course_assignment'] = self.get_course_assigment()
        ctx['back_url'] = self.request.GET.get('back') or self.object.programme.get_absolute_url()
        return ctx

    def get_course_assigment(self):
        return self.object.courseassignment_set.all()

    def get_back_url(self):
        return self.request.GET.get('back') or self.object.programme.get_absolute_url()


class StudentCourseListView(LoginRequiredMixin, ListView):
    template_name = 'course/student/home.html'
    model = Course
    course_query_var = "qcourse"

    def get_context_data(self, **kwargs):
        ctx = super(StudentCourseListView, self).get_context_data(**kwargs)
        ctx['title'] = 'Student Courses'
        ctx['header'] = 'Your Courses'
        ctx['course_query_var'] = self.course_query_var
        ctx['course_query_data'] = self.request.GET.get(self.course_query_var)
        ctx['current_semester'] = self.current_semester
        ctx['back_url'] = get_back_url(self.request) or reverse("Student:home")
        return ctx

    @property
    def current_semester(self):
        return SemesterAcademicYearModel.objects.filter(is_current=True).first()

    def get_queryset(self):
        student = self.get_student()
        searched_query = self.request.GET.get(self.course_query_var)
        filter_kwargs = dict(
            programme=student.programme,
        )
        if searched_query:
            return self.model.objects.filter(
                models.Q(code__icontains=searched_query) | models.Q(name__icontains=searched_query),
                **filter_kwargs
            )

        return self.model.objects.filter(
            semester=self.current_semester,
            level=student.level,
            **filter_kwargs)

    def get_student(self):
        return self.request.user.student


@login_required
def get_students_other_courses(request):
    student = request.user.student
    courses = Course.objects.filter(programme__student=student)
    data = [{'name': course.name, 'semester': course.semester.name,
             'lecturer': course.lecturer.profile.get_full_name() if course.lecturer else None,
             'level': str(course.level), 'link': reverse('Course:stu_details', kwargs={'course_code': course.code}), }
            for course in courses]
    return JsonResponse(data={
        "courses": data
    })


class StaffCourseListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Course
    permission_required = 'course.view_courses_list'
    template_name = 'course/staff/list.html'
    filter_form_cls = CourseFilter
    paginate_by = 100

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(StaffCourseListView, self).get_context_data(object_list=object_list, **kwargs)
        ctx['title'] = 'All Course'
        ctx['header'] = 'courses'
        ctx['back_url'] = get_back_url(self.request) or reverse('Dashboard:admin')
        ctx['total_course'] = self.model.objects.count()
        ctx['filter_form'] = self.get_form
        return ctx

    @property
    def get_form(self):
        form = self.filter_form_cls(data=self.request.POST or None)
        form.is_valid()
        return form

    def get_paginate_by(self, queryset):
        try:
            paginate_by = self.request.POST.get('paginate_by') or self.get_form.cleaned_data['paginate_by']
            self.request.session["paginate_by"] = paginate_by
            return paginate_by
        except AttributeError:
            return self.request.session.get("paginate_by") or 100

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_queryset(self):
        form = self.get_form
        if form.is_valid():
            clean_data = form.cleaned_data
            return self.model.objects.search(
                name_start=clean_data.get('name_start_with'),
                name=clean_data.get('name'),
                code=clean_data.get('course_code'),
                programme_name=clean_data.get('programme_name'),
            )
        else:
            return super(StaffCourseListView, self).get_queryset()


class StudentCourseDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Course
    permission_required = 'course.view_course'
    template_name = 'course/student/details.html'
    permission_denied_message = 'You need permission to view course details'

    def get_context_data(self, **kwargs):
        ctx = super(StudentCourseDetail, self).get_context_data(**kwargs)
        ctx['title'] = '%s Details' % self.object
        ctx['back_url'] = get_back_url(self.request)
        return ctx

    def get_object(self, queryset=None):
        try:
            return self.model.objects.get(code=self.kwargs['course_code'])
        except self.model.DoesNotExist:
            raise Http404('The Course is not present!')


class LecturerCoursesListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Course
    permission_required = 'course.view_courses_list'
    template_name = 'course/lecturer/list.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(LecturerCoursesListView, self).get_context_data(object_list=object_list, **kwargs)
        ctx['back_url'] = get_back_url(self.request)
        ctx['header'] = 'Your Current Courses'
        ctx['title'] = 'Your Courses'
        ctx['q'] = self.request.GET.get('q')
        ctx['info'] = f""" "{ctx['q']}" matches """ if ctx['q'] else 'Showing'
        return ctx

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return self.model.objects.search_by_name_code(query=query,
                                                          courseassignment__lecturer__profile=self.request.user,
                                                          courseassignment__is_tutor=True)
        return self.model.objects.filter(courseassignment__lecturer__profile=self.request.user,
                                         courseassignment__is_tutor=True)


class CourseAssignmentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = CourseAssignment
    permission_required = 'course.add_courseassignment'
    form_class = CourseAssignmentForm
    template_name = 'course/courseassignment/create.html'
    permission_denied_message = 'You need permission to assign course to a lecturer'

    def get_success_url(self):
        return get_next_url(self.request) or get_back_url(self.request)

    def get_context_data(self, **kwargs):
        ctx = super(CourseAssignmentCreateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Assign Course to Lecturer'
        ctx['header'] = "Select the lecturer"
        ctx['back_url'] = get_back_url(self.request)
        ctx['course_name'] = self.get_course().name
        return ctx

    def get_course(self):
        return get_object_or_404(Course, code=self.kwargs.get('course_code'))

    def get_initial(self):
        initial = super(CourseAssignmentCreateView, self).get_initial()
        if not initial:
            initial = {}
        initial['course'] = self.get_course()
        return initial

    def form_valid(self, form):
        form.instance.course = self.get_course()
        form.instance.assigned_by = self.request.user
        return super(CourseAssignmentCreateView, self).form_valid(form)


class CourseAssigmentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'course.change_courseassignment'
    permission_denied_message = 'You need permission to change course assignment'
    model = CourseAssignment
    form_class = CourseAssignmentForm
    pk_url_kwarg = 'courseassignmentpk'
    template_name = 'course/courseassignment/create.html'

    def get_success_url(self):

course/templates/course/staff/create.html
{% extends 'base/admin/create.html' %}

{% block scripts %}
    <script>
        let nameCodeElm = document.getElementById('IDnameCode');
        nameCodeElm.children[0].classList.add('flex-grow-1');
        {#for (let n=0; n <nameCodeElm.children.length; n++){#}
        {#    nameCodeElm.children[n].classList.add('flex-grow-1');#}
        {# } #}

        let descriptionElm = document.getElementById('div_{{ form.description.id_for_label }}');
        for (let n=0; n<descriptionElm.children.length; n++){
            descriptionElm.children[n].classList.add('d-block')
        }
    </script>
{% endblock %}

course/templates/course/staff/detail.html
{% extends 'base/admin/base.html' %}

{% block container %}
    <div class="container">
        <div class="row">
            <div class="col">
                <a href="{{ back_url }}" class="btn btn-link" onclick="spinBack(this)"><span class="fa fa-chevron-left"></span> back</a>
            </div>
        </div>

        <div class="row my-4">
            <div class="col-auto mx-auto text-center">
                <small>Course</small>
                <h4>{{ course }}</h4>
            </div>
        </div>

        <div class="row my-4">
            <div class="col">
                <div class="card-group shadow-sm">
                    <div class="card bg-light-gold text-gold">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <span>Details</span>
                                <span class="fa fa-address-card"></span>
                            </div>
                            <table class="table">
                                <tr>
                                    <td>Name</td>
                                    <td>{{ course.name }}</td>
                                </tr>
                                <tr>
                                    <td>Code</td>
                                    <td>{{ course.code }}</td>
                                </tr>
                                 <tr>
                                    <td>Semester</td>
                                    <td>{{ course.semester }}</td>
                                </tr>
                                 <tr>
                                    <td>Level</td>
                                    <td>{{ course.level }}</td>
                                </tr>
                                <tr>
                                    <td>Credit Hours</td>
                                    <td>{{ course.credit_hours }}</td>
                                </tr>
                                <tr>
                                    <td>Created by</td>
                                    <td>{{ course.created_by }}</td>
                                </tr>
                            </table>
                            <span>last modified: {{ course.updated_at }}</span>
                        </div>
                    </div>
                    <div class="card bg-light-gold text-gold">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <span>Programme</span>
                                <span class="fa fa-address-card"></span>
                            </div>
                            <table class="table">
                                <tr>
                                    <td>Programme</td>
                                    <td>{{ course.programme }}</td>
                                </tr>
                                <tr>
                                    <td>Department</td>
                                    <td>{{ course.programme.department }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row my-4">
            <div class="col">
                <div class="p-2 shadow-sm rounded bg-light-gold d-flex justify-content-between align-items-center">
                    <span>Course Assignment Activity</span>
                    <a href="{% url 'Course:assign2another' course_code=course.code %}?back={{ request.path }}" class="btn btn-warning">Assign to Another Lecturer</a>
                </div>
            </div>
        </div>
        {% if course_assignment %}
            <div class="row my-4">
                <div class="col-12">
                    <span>Course Lecturers:</span>
                </div>
                {% for course_lecturer in course_assignment %}
                    <div class="col-md-4 col-lg-3 my-2" id="cl{{ course_lecturer.id }}">
                        <div class="card hover_shadow">
                            {% with course_lecturer.lecturer.profile as profile %}
                                <img src="{{ profile.picture.url }}" alt="" class="img-fluid">

                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <small>Identity</small><br>
                                    <b>{{ course_lecturer.lecturer.identity }}</b>
                                </li>
                                <li class="list-group-item">
                                    <small>Name</small><br>
                                    <b>{{ profile.get_full_name }}</b>
                                </li>

                                {% if course_lecturer.is_tutor %}
                                    <li class="list-group-item p-3 list-group-item-success">
                                        <small>Status</small><br>
                                        <b class="mx-1">Is current tutor </b>
                                    </li>
                                {% else %}
                                    <li class="list-group-item p-3 list-group-item-danger">
                                        <small>Status</small><br>
                                        <b class="mx-1">Is not current tutor </b>
                                    </li>
                                {% endif %}
                                <li class="list-group-item">
                                    <small>Date Time Assigned</small><br>
                                    <b>{{ course_lecturer.timestamp }}</b>
                                </li>
                                <li class="list-group-item">
                                    <small>Assigned By</small><br>
                                    <span class="text-muted" title="{{ course_lecturer.assigned_by.get_full_name }}">{{ course_lecturer.assigned_by }}</span>
                                </li>

                            </ul>

                            {% endwith %}
                        <div class="card-footer d-flex flex-column gap-2 flex-lg-row ">
                            <div class="flex-grow-1">
                                <a href="{{ course_lecturer.get_absolute_update_url }}?back={{ request.path }}" class="w-100 btn {% if course_lecturer.is_tutor %} btn-warning">Unmake Tutor {% else %} btn-primary"> Make Tutor {% endif %}</a>
                            </div>
                            <div class="flex-grow-1">
                                <button onclick="reMoveLecturer('{% url "Course:rm_lec_short_info" user_slug=course_lecturer.lecturer.slug assignment_id=course_lecturer.id %}')" class="w-100 btn btn-danger ">Remove</button>
                            </div>

                        </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        {% else %}
            <div class="row my-4">
                <div class="col-md-6 mx-auto">
                    <div class="alert alert-dark text-center">
                        <span>This course has not been assigned to a lecturer yet!</span>
                        <hr>
                        <span>Its also has no previous assigned lecturers.</span>
                    </div>
                </div>
            </div>
        {% endif %}

        {% if course.description %}
            <div class="row my-4">
                <div class="rounded p-2 bg-light-gold">
                    <h5 class="align-self-center">Description</h5>
                </div>
                <div class="col-md-8 mx-auto">
                    <p>{{ course.description|safe }}</p>
                </div>
            </div>
        {% endif %}
    </div>

    <section>
        {% include 'base/modelFooterless.html' %}
    </section>
{% endblock %}

{% block scripts %}
    <script>
        function reMoveLecturer(url) {
            modalTitle.innerText = 'Remove Lecturer ';
            modalBody.innerHTML = '<p class="text-center mt-2"><span class="fa fa-spinner fa-spin fa-2x"></span></p> <p class="text-center">Loading lecturer information ...</p>'
            toggleModal()
            $.ajax({
                url:url,
                success: response => {
                    modalBody.innerHTML = `<div>
<img src="${response.picture_src}" alt="" class="img-fluid">
<ul class="list-group">
<li class="list-group-item"><small>Name</small><br><b>${response.full_name}</b></li>
<li class="list-group-item"><small>Email</small><br><b>${response.email}</b></li>
<li class="list-group-item"><small>Department</small><br><b>${response.department}</b></li>
</ul>
<button class="btn btn-warning w-100 my-2" onclick="remove4rmCourse('${response.removedUrl}', ${response.assignId})">Remove From Course</button>
</div>`
                }
            })
        }

        function remove4rmCourse(rmUrl, id) {
            const elem = document.getElementById("cl"+id);
                $.ajax({
                    url: rmUrl,
                    success: response => {
                        alert(response.description)
                    }
                })
            toggleModal();
            elem.remove();
        }
    </script>
{% endblock scripts %}

course/templates/course/staff/list.html
{% extends 'base/admin/base.html' %}
{% load static %}
{% block container %}
    <div class="container">
        <div class="row">
            {% if back_url %}
                {% include 'institution/utils/back_snippet.html' %}
            {% endif %}
            <div class="col-auto mx-auto">
                <h4 class="text-center display-6">{{ header|upper }}</h4>
            </div>
        </div>
        <div class="row my-3">
            <div class="col-12 bg-light-gold p-2 rounded shadow-sm">
                <div class="d-flex justify-content-between align-items-center">
                    <span>Now <b>showing {{ page_obj.object_list.count }}</b> out of <b>{{ total_course }} courses</b></span>
                    <button onclick="filterCourse()" class="btn bg-gold text-white hover_shadow"><span class="fa fa-filter me-2 "></span> Filter</button>
                </div>
            </div>
        </div>
        <div class="row my-3">
            <div class="table-responsive my-2">
                <table class="table ">
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Course Code</th>
                        <th>Credit Hours</th>
                        <th>Semester</th>
                        <th>Level</th>
                        <th>Programme</th>
                        <th></th>
                    </tr>

                    {% for course in object_list %}
                        <tr class="hover_shadow">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ course.name }}</td>
                            <td>{{ course.code }}</td>
                            <td>{{ course.credit_hours }}</td>
                            <td>{{ course.semester }}</td>
                            <td>{{ course.level }}</td>
                            <td>{{ course.programme }}</td>
                            <td><a href="{{ course.get_absolute_url }}?back={{ request.path }}" class="btn btn-primary btn-sm">View</a></td>
                        </tr>
                    {% endfor %}
                </table>
                </div>
        </div>
    </div>

    <article>
        {% include 'base/modelFooterless.html' with m_form=filter_form %}
    </article>

    <section class="container">
        <div class="row">
            <div class="col">
                <div class="pagination">
                    {% if page_obj.has_previous %}
                        <span class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                        </span>
                    {% endif %}
                    {% for pg in  paginator.get_elided_page_range %}
                        {% if pg == page_obj.number %}
                            <span class="page-item disabled">
                                <a class="page-link">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </a>
                            </span>
                        {% else %}
                            <span class="page-item">
                                <a href="?page={{ pg }}" class="page-link">{{ pg }}</a>
                            </span>
                        {% endif %}


                    {% endfor %}
                    {% if page_obj.has_next %}
                        <span class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        </span>
                        <span class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                        </span>
                    {% endif %}
                </div>

            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script>
        function filterCourse() {
            modalTitle.innerText = 'Filter Courses By:'
            toggleModal();
        }
    </script>
{% endblock %}