CollegeManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('admission/', include('admission.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/', include('student.urls')),
    path('address/', include('address.urls')),
    path('employmentHistory/', include('empoymentHistory.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('faculty/', include('faculty.urls')),
    path('department/', include('department.urls')),
    path('institution/', include('INSTITUTION.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('system/', include('system.urls')),
    path('course/', include('course.urls')),
    path('lecturer/', include('lecture.urls')),
    path('klassrm/', include('classRoom.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from .views import LandingPage, AboutUsPage, INSTITUTION_NAME, LoginPage, LogoutPage, AdministratorHomePage
from django.urls import path

app_name = 'Home'
urlpatterns = [
    path('', LandingPage.as_view(), name='landing_page'),
    path('about'+INSTITUTION_NAME.get('institution_short_name').lower(), AboutUsPage.as_view(), name="about_institution"),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('administration/', AdministratorHomePage.as_view(), name='admin'),
]

department/urls.py
from django.urls import path, include

from .views import (
    DepartmentsListView,
    DepartmentCreateView,
    DepartmentDetailView,
    DepartmentUpdateView,
    DepartmentDeleteView,
    FacultyDepartmentListView
)


app_name = 'Department'
department_urlpatterns = [
    path('all/', DepartmentsListView.as_view(), name='list'),
    path('add/', DepartmentCreateView.as_view(), name='create'),
    path('<slug:slug>/', DepartmentDetailView.as_view(), name='detail'),
    path('change/<slug:slug>/', DepartmentUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', DepartmentDeleteView.as_view(), name='delete'),
    path('inthisfaculty/<slug:faculty_slug>/', FacultyDepartmentListView.as_view(), name='4faculty')
]


urlpatterns = [
    path('', include(department_urlpatterns)),
    path('programme/', include('programme.urls')),
]

faculty/urls.py
from django.urls import path

from .views import (
    FacultyCreationView,
    FacultyListView,
    FacultyDetailView,
    FacultyUpdateView,
    FacultyDeleteView,
)

app_name = 'Faculty'
urlpatterns = [
    path('add/', FacultyCreationView.as_view(), name='create'),
    path('list/', FacultyListView.as_view(), name='list'),
    path('detail/<slug:slug>/', FacultyDetailView.as_view(), name='detail'),
    path('edit/<slug:slug>/', FacultyUpdateView.as_view(), name='change'),
    path('delete/<slug:slug>/', FacultyDeleteView.as_view(), name='delete'),

]

faculty/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.dispatch import receiver
from django.utils.text import slugify
from django.shortcuts import reverse
from CollegeManagementSystem import validation


def upload_picture_to(instance, filename):
    import os
    new_filename = 'picture' + os.path.splitext(filename)[-1]
    return os.path.join('faculty', instance.name, new_filename)


def upload_icon_to(instance, filename):
    import os
    new_filename = 'icon' + os.path.splitext(filename)[-1]
    return os.path.join('faculty', instance.name, new_filename)


class FacultyManager(models.Manager):
    def search(self, query: str):
        if query:
            return self.filter(
                name__icontains=query,
            )
        else:
            return self.all()


class Faculty(models.Model):
    name = models.CharField(max_length=120, unique=True, validators=(validation.validate_alphanumberic_space,),
                            help_text='Name of Faculty,College, or School'
                            )
    slug = models.SlugField(unique=True)
    icon = models.ImageField(help_text='Faculty icon', upload_to=upload_icon_to)
    picture = models.ImageField(help_text='Picture of the faculty building, student , etc.', upload_to=upload_picture_to)
    note = RichTextField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    objects = FacultyManager()

    class Meta:
        db_table = 'faculty'
        verbose_name_plural = 'Faculties'
        verbose_name = 'Faculty'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('Faculty:detail',
                       kwargs={
                        "slug": self.slug
                       })

    def get_absolute_change_url(self):
        return reverse('Faculty:change',
                       kwargs={
                        "slug": self.slug
                       })

    def get_absolute_delete_url(self):
        return reverse('Faculty:delete',
                       kwargs={
                        "slug": self.slug
                       })


@receiver(models.signals.pre_save, sender=Faculty)
def auto_slug_faculty(instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)

faculty/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import StrictButton, FormActions, UneditableField
from crispy_forms.layout import HTML, Div

from .models import Faculty


class FacultyCreationForm(forms.ModelForm):
    class Meta:
        model = Faculty
        exclude = ('slug', )
        widgets = {
            'picture': forms.FileInput(attrs={'type': 'file'}),
            'icon': forms.FileInput(attrs={'type': 'file'}),
        }

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.form_method = 'POST'
        helper.layout.append(
            FormActions(
                StrictButton('Reset', type='reset', css_class='btn btn-light'),
                StrictButton('Save', css_class='btn btn-primary', type='submit'),
                css_class='d-flex justify-content-end'
            )
        )

        return helper


class FacultyChangeForm(forms.ModelForm):
    class Meta:
        fields = ('name', 'icon', 'picture', 'note')
        model = Faculty

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.form_method = 'POST'
        helper['slug'].wrap(UneditableField)
        helper.layout.append(
            FormActions(
                Div(css_id='repalceWBtn')
                ,
                Div(
                StrictButton('Reset', type='reset', css_class='btn btn-light'),
                StrictButton('Save', css_class='btn btn-primary', type='submit'),
                    css_class='align-self-end', css_id='resetBtn'
                ),
            )
        )

        return helper

faculty/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .forms import Faculty, FacultyCreationForm, FacultyChangeForm
from department.models import Department


class FacultyCreationView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Faculty
    form_class = FacultyCreationForm
    template_name = 'faculty/admin/create.html'
    permission_required = 'faculty.add_faculty'
    permission_denied_message = 'You need permission to add faulty'

    def get_context_data(self, **kwargs):
        ctx = super(FacultyCreationView, self).get_context_data(**kwargs)
        ctx['title'] = 'Add Faculty'
        ctx['header'] = 'Add New Faculty'
        return ctx

    def get_success_url(self):
        return self.object.get_absolute_url()


class FacultyListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Faculty
    permission_required = 'faculty.view_faculty'
    template_name = 'faculty/admin/listview.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(FacultyListView, self).get_context_data(object_list=object_list, **kwargs)
        ctx['title'] = 'Faculties'
        ctx['header'] = 'All Faculties in this Institution'
        ctx['empty_text'] = '"%s" matches no faculty in the system' % self.searched_query if self.searched_query else\
            'There are no faculties in the system'
        ctx['facultyQry'] = self.searched_query
        ctx['hadPerms'] = self.request.user.has_perms(('faculty.change_faculty',  'faculty.add_faculty'))
        return ctx

    @property
    def searched_query(self):
        return self.request.GET.get('facultyQry')

    def get_login_url(self):
        return reverse('Home:login')

    def get_queryset(self):
        return self.model.objects.search(self.searched_query)


class FacultyDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    template_name = 'faculty/admin/view.html'
    model = Faculty
    permission_required = 'faculty.view_faculty'

    def get_context_data(self, **kwargs):
        ctx = super(FacultyDetailView, self).get_context_data(**kwargs)
        ctx['title'] = self.object.name + ' - details'
        ctx['departments'] = self.get_department_queryset()
        ctx['has_department_perm'] = self.can_user_add_department()
        ctx['has_faculty_perm'] = self.can_user_change_faculty()
        ctx['all_departments_count'] = self.get_departments_count()
        return ctx

    def get_departments_count(self):
        return Department.objects.get_for_faculty(self.object.slug).count()

    def get_department_queryset(self):
        # return the first 6 departments
        return Department.objects.get_for_faculty(self.object.slug)[:6]

    def can_user_add_department(self):
        return self.request.user.has_perm('department.add_department')

    def can_user_change_faculty(self):
        return self.request.user.has_perm('faculty.change_faculty')


class FacultyUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Faculty
    template_name = 'faculty/admin/edit.html'
    permission_required = 'faculty.change_faculty'

    def get_context_data(self, **kwargs):
        ctx = super(FacultyUpdateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Edit %s' % self.object.name
        ctx['header'] = 'Edit %s Faculty' % self.object.name
        return ctx

    def get_form_class(self):
        return FacultyChangeForm


class FacultyDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Faculty
    template_name = 'faculty/admin/delete.html'
    permission_required = 'delete_faculty'
    permission_denied_message = 'You need permission to delete this faculty from the system'

    def get_context_data(self, **kwargs):
        ctx = super(FacultyDeleteView, self).get_context_data(**kwargs)
        ctx['title'] = 'Delete %s' % self.object.name
        ctx['header'] = 'Delete %s' % self.object.name
        ctx['departments'] = self.get_department_set()
        return ctx

    def get_success_url(self):
        return reverse('Faculty:list')

    def get_department_set(self):
        return Department.objects.get_for_faculty(self.object.slug)

faculty/templates/faculty/admin/create.html
{% extends 'base/admin/create.html' %}



{% block scripts %}
    <script>
        let noteElm = document.getElementById('{{ form.note.id_for_label }}').parentElement;
        noteElm.classList.add('d-block');
        noteElm.classList.add('table-responsive')
    </script>
{% endblock %}

faculty/templates/faculty/admin/delete.html
{% extends 'base/admin/base.html' %}

{% block header %}
    <style>
        body {
            background-image: url("{{ faculty.picture.url }}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
{% endblock %}

{% block container %}
    <div class="container">
        <div class="row my-3">
            <div class="col-md-auto mx-auto">
                <h4 class="text-center">{{ header }} Faculty</h4>
                <hr>
                <div class="card shadow transparent-bg" style="background-color: rgba(255,255,255,0.64)">
                    <div class="card-img-top text-center">
                        <img src="{{ faculty.icon.url }}" alt="" class="img-fluid">
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table">
                            <tr>
                                <td>Name</td>
                                <td>{{ faculty.name }}</td>
                            </tr>
                            <tr>
                                <td>Note</td>
                                <td class="overflow-wrap" style="overflow-wrap: anywhere;"><p>{{ faculty.note|safe }}</p></td>
                            </tr>
                            <tr>
                                <td>Date created</td>
                                <td>{{ faculty.timestamp }}</td>
                            </tr>
                        </table>
                        <div class="d-flex justify-content-center">
                            <div class="alert alert-warning width-fit-content" style="width: fit-content">
                            <p class="">
                                Deleting this faculty will affect all department and programmes under it.
                            </p>
                            {% if departments %}
                                <ol>
                                {% for department in departments %}
                                    <li>{{ department }} Department</li>
                                    {% if department.programmes %}
                                        <ol type="a">
                                            {% for programme in department.programmes %}
                                                <li>{{ programme }} Programme</li>
                                            {% endfor %}
                                        </ol>
                                    {% endif %}
                                {% endfor %}
                                </ol>
{#                                TODO Link this to a more detail page #}
                                <p class="text-danger"><span class="fa fa-exclamation-triangle"></span> It is not safe to delete this faculty</p>
                            {% endif %}
                            <hr>
                            <span>
                                <span class="fa fa-exclamation-circle"></span> This operation is not reversible
                            </span>
                        </div>
                        </div>
                        <form method="post">
                            <div class="d-flex justify-content-end gap-3">
                                {% csrf_token %}
                                <a href="{{ faculty.get_absolute_url }}" class="btn btn-secondary" onclick="dynamicSpinner(this)">Cancel</a>
                                <button type="submit" class="btn btn-danger" onclick="dynamicSpinner(this)">Delete Faculty</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

faculty/templates/faculty/admin/edit.html
{% extends 'base/admin/create.html' %}



{% block scripts %}
    <script>
        let noteElm = document.getElementById('{{ form.note.id_for_label }}').parentElement;
        noteElm.classList.add('d-block');
        noteElm.classList.add('table-responsive');

        let backBtn= document.getElementById('resetBtn');
        backBtn.parentElement.classList.add('d-flex');
        backBtn.parentElement.classList.add('justify-content-between');

        document.getElementById('repalceWBtn').insertAdjacentHTML('afterbegin',
            '<a href="{{ faculty.get_absolute_url }}" id="backBtn" class="btn btn-outline-secondary" onclick="dynamicSpinner(this)"><span class="fa fa-chevron-left"> </span> back </a>'
        )
    </script>
{% endblock %}

faculty/templates/faculty/admin/listview.html
{% extends 'base/admin/base.html' %}
{% load crispy_forms_tags %}

{% block container %}
    <div class="container">
        <div class="row my-3">
            <div class="col-auto mx-auto">
                <h4 class="text-center">{{ header }}</h4>
            </div>
        </div>

            <div class="row my-3">
                <div class="col">
                    <div class="bg-light rounded d-flex gap-2 flex-column flex-md-row justify-content-between align-items-center p-2">
                        {% if hadPerms %}
                            <div class="">
                                <a onclick="dynamicSpinner(this)" href="{% url 'Faculty:create' %}" class="btn btn-primary">Faculty <span class="fa fa-plus-circle me-2"></span></a>
                            </div>
                        {% endif %}
                       {% if facultyQry %}
                           <div class="">
                                <span><b>"{{ facultyQry }}"</b> matches {{ faculty_list.count }} faculties</span>
                           </div>
                       {% else %}
                           <h5>{{ faculty_list.count }} faculties</h5>
                       {% endif %}
                        <form method="get" class="align-self-end">
                            <div class="input-group">
                                <input type="text" value="{{ facultyQry|default:'' }}" name="facultyQry" class="form-control" placeholder="Search Faculty">
                                <button onclick="dynamicSpinner(this)" type="submit" class="btn btn-info text-white" title="search"><span class="fa fa-search me-2"></span></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

       {% if faculty_list %}
           <div class="row">
               {% for faculty in faculty_list %}
                   <div class="col-md-4 my-3">
                        {% if faculty.picture %}
                            <div class="card h-100 hover_shadow-long" style="background: url({{ faculty.picture.url }}); background-size: cover; background-position: center; background-attachment: scroll">
                        {% else %}
                            <div class="card h-100">
                        {% endif %}
                            <a href="{{ faculty.get_absolute_url }}" class="text-decoration-none bg-transparent">
                                <div class="bg-light card-body d-flex flex-column align-items-center gap-3 bg-transparent">
                                    {% if faculty.icon %}
                                        <img src="{{ faculty.icon.url }}" alt="" width="64" height="64" class="align-self-center transparent-bg p-1 rounded">
                                    {% else %}
                                        <span class="fa fa-school fa-4x"></span>
                                    {% endif %}
                                    <h4 class="alert bg-white50 transparent-bg">{{ faculty.name }}</h4>
                                </div>
                            </a>
                        </div>
                   </div>
               {% endfor %}
           </div>

       {% else %}
           <div class="row">
               <div class="col-md-6 mx-auto">
                   <div class="card">
                       <div class="card-body d-flex align-items-center flex-column gap-3">
                           <span class="fa fa-box-open fa-3x"></span>
                           <p class="p-0 m-0">{{ empty_text }}</p>
                           <a  class="btn btn-link text-decoration-none" href="{% url 'Faculty:create' %}"  onclick="rotateElement(this)">add a faculty <span class="fa fa-plus-circle me-2" id="addFaculty"></span></a>
                       </div>
                   </div>
               </div>
           </div>
       {% endif %}
    </div>
{% endblock %}

faculty/templates/faculty/admin/view.html
{% extends 'base/admin/base.html' %}

{% block header %}
    <style>
        .faculty_toBg {
            background-image: url("{{ faculty.picture.url|default:'' }}");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }
        .min-height-40 {
            min-height: 50vh;
        }
    </style>
{% endblock %}
{% block container %}
    <div class="container-fluid faculty_toBg  bg-light">
        <div class="row  d-flex justify-content-center flex-column">
            <div class="col-auto align-self-end p-2 gap-3">
                <a href="{{ faculty.get_absolute_change_url }}" class="btn transparent-bg shadow text-primary" onclick="dynamicSpinner(this)">Edit Faculty <span class="fa fa-edit ml-2"></span></a>
                <a href="{{ faculty.get_absolute_delete_url }}" class="btn transparent-bg shadow bg-light-red " onclick="dynamicSpinner(this)">Delete Faculty <span class="fa fa-trash ml-2"></span></a>
            </div>
            <div class="col-auto min-height-40 mx-auto align-self-center d-flex justify-content-center flex-column">
                <div class="p-1 rounded-pill transparent-bg shadow-sm">
                    <h1 class="text-black-50 text-center ">{{ faculty.name }}</h1>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row my-3">
{#            {% if faculty.note %}#}
            <div class="col-12  mb-4">
                    <div class="card-body" title="notes">
                        <div class="text-center mb-2">
                            <img src="{{ faculty.icon.url|default:'' }}" alt="{{ faculty }}" class="img-fluid" height="60" width="80">
                            <h4>{{ faculty }}</h4>
                        </div>
                        {% if faculty.note %}
                            <p>{{ faculty.note|safe }}</p>
                        {% elif has_faculty_perm %}
                            <div class="text-center">
                                <a onclick="dynamicSpinner(this)" href="{{ faculty.get_absolute_change_url }}#div_id_note" class="btn btn-link">add faculty notes</a>
                            </div>
                        {% endif %}
                    </div>
            </div>
{#            {% endif %}#}
            <div class="col-md-6  mb-4 mx-auto">
                <div class="card h-100">
                    <div class="card-body">
                        <div class=" text-center gap-3">
                            <span class="fa fa-building fa-4x"></span>
                            <h5>Faculty Departments ({{ all_departments_count }})</h5>
                        </div>
                            {% if departments %}
                            <span class="">Departments list</span>

                            <div class="list-group">
                                {% for department in departments %}
                                    <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center" onclick="dynamicSpinner(this)" href="{{ department.get_absolute_url }}?back={{ request.path }}&backname={{ faculty.name }}">{{ department.name }} <span class="fa fa-chevron-right"></span></a>
                                {% endfor %}
                            </div>
                            {% else %}
                                <div class="text-center">
                                    <p>This faculty has no department yet</p>
                                    {% if has_department_perm %}
                                        <a href="{% url 'Department:create' %}?facultyslug={{ faculty.slug }}" class="btn btn-link" onclick="dynamicSpinner(this)">add department to this faculty</a>
                                    {% endif %}
                                </div>
                            {% endif %}
                    </div>
                    {% if departments %}
                        <div class="p-2 d-flex justify-content-end">
                            {% if has_department_perm %}
                                <a href="{% url 'Department:create' %}?facultyslug={{ faculty.slug }}" class="btn btn-link" onclick="rotateElement(this)"><span class="fa fa-plus me-2"></span> department</a>
                            {% endif %}
                            <a href="{% url 'Department:4faculty' faculty_slug=faculty.slug %}?back={{ request.path }}&backname={{ faculty.name }}" class="btn btn-light" onclick="dynamicSpinner(this)">ALL <span class="fa fa-th-list ms-2"></span> <span class="fa fa-chevron-right ms-2"></span></a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="row my-3">
            <div class="col-md-6 mb-4 mb-md-0">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-center align-items-center gap-3">
                        <span class="fa fa-user-tie fa-4x"></span>
                        <h5>Faculty Staffs</h5>
                        <h4>---</h4>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-4 mb-md-0">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-center align-items-center gap-3">
                        <span class="fa fa-user-tie fa-4x"></span>
                        <h5>Faculty Facilities</h5>
                        <h4>---</h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}