CollegeManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('admission/', include('admission.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/', include('student.urls')),
    path('address/', include('address.urls')),
    path('employmentHistory/', include('empoymentHistory.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('faculty/', include('faculty.urls')),
    path('department/', include('department.urls')),
    path('institution/', include('INSTITUTION.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('system/', include('system.urls')),
    path('course/', include('course.urls')),
    path('lecturer/', include('lecture.urls')),
    path('klassrm/', include('classRoom.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from .views import LandingPage, AboutUsPage, INSTITUTION_NAME, LoginPage, LogoutPage, AdministratorHomePage
from django.urls import path

app_name = 'Home'
urlpatterns = [
    path('', LandingPage.as_view(), name='landing_page'),
    path('about'+INSTITUTION_NAME.get('institution_short_name').lower(), AboutUsPage.as_view(), name="about_institution"),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('administration/', AdministratorHomePage.as_view(), name='admin'),
]

accounts/urls.py
from django.urls import path, include

from .views import (
    StudentProfileCreateView,
    ContinuouStudentProfileCreateView,
    LecturerProfileCreateView,
    SetPassword4other,
    SetNewPassword,
    logout_to_homepage,
    LectureAccountDetails,
)

app_name = 'Accounts'

urlpatternsAjax = [
    path('staffsetpassword/<str:identity>/', SetPassword4other.as_view(), name='staff_set_password'),
]

lecturer_urlpatterns = [
    path('profile/', LectureAccountDetails.as_view(), name='lec_detail'),
]

urlpatterns = [
    path('studentadmission/profile/<str:serial_number>/',
         StudentProfileCreateView.as_view(), name='admission_student_profile'),
    path('add/student/profile/<str:index_number>/',
         ContinuouStudentProfileCreateView.as_view(), name='create_student_profile'),
    path('add/lecturer/<str:identity>/', LecturerProfileCreateView.as_view(), name='create_lecturer'),
    path('ajax/', include(urlpatternsAjax)),
    path('setnewpassword/', SetNewPassword.as_view(), name='set_pwd'),
    path('logout/', logout_to_homepage, name='logout'),
    path('lecturer/self/', include(lecturer_urlpatterns)),
]

address/urls.py
from django.urls import path
from .views import (
    StudentAddressCreateView,
    UserAddressCreateView,
)


app_name = 'Address'
urlpatterns = [
    path('studentaddress/create/', StudentAddressCreateView.as_view(), name='admission_student_create'),
    path('staff/create/<str:profile_slug>/', UserAddressCreateView.as_view(), name='staff_student_create'),
]

admission/urls.py
from django.urls import path, include

from .views import (
    AdmissionMainTemplateView,
    StudentFormLoginTemplateView,
    AdmissionAdministrationTemplateView,
    AllAdmissionFormsListView,
    StudentFormsDetailView,
    StudentFormsAcceptView,
    StudentFormsPrintView,
    StudentFormSubmitView,
    AdmissionFormCreateView,
    AdmissionFormDetailView,
    AdmissionFormChangeView,
    AdmissionCreateBatchFormsView,
    AdmissionBatchCreatedView,
    FormTypeModelCreateView,
    FormTypeModelListView,
    FormTypeModeDetailView,
    FormTypeModelChangeView,
    HandleAdmissionExceptions,
    FormTypeModelDelete,
)


app_name = 'Admission'
student_admission_urlpatterns = [
    path('', AdmissionMainTemplateView.as_view(), name='main_template_page'),
    path('login/<int:formtypeid>/', StudentFormLoginTemplateView.as_view(), name='login'),
    path('printforms/', StudentFormsPrintView.as_view(), name='stu_print_form'),
    path('submitforms/', StudentFormSubmitView.as_view(), name='stu_submit_form'),
    path('exceptionhandle/', HandleAdmissionExceptions.as_view(), name='handle_exceptions'),
]

staff_urlpatterns = [
    path('allforms/', AllAdmissionFormsListView.as_view(), name='allforms'),
    path('', AdmissionAdministrationTemplateView.as_view(), name='admins'),
    path('add/', AdmissionFormCreateView.as_view(), name='create'),
    path('change/<str:serial_number>/<int:id>/', AdmissionFormChangeView.as_view(), name='change'),
    path('formsdetails/<str:serial_number>/<int:id>/', StudentFormsDetailView.as_view(), name='form_details'),
    path('acceptform/<str:serial_number>/<int:id>/', StudentFormsAcceptView.as_view(), name='accept_form'),
    path('detail/<str:serial_number>/', AdmissionFormDetailView.as_view(), name='detail'),
    path('generatebatch/', AdmissionCreateBatchFormsView.as_view(), name='create_batch'),
    path('generatebatch/completed/', AdmissionBatchCreatedView.as_view(), name='batch_job_result'),
    path('formtype/add/', FormTypeModelCreateView.as_view(), name='form_type_create'),
    path('formtype/list/', FormTypeModelListView.as_view(), name='form_type_list'),
    path('formtype/detail/<str:title>/<int:id>', FormTypeModeDetailView.as_view(), name='form_type_detail'),
    path('formtype/change/<str:title>/<int:id>', FormTypeModelChangeView.as_view(), name='form_type_update'),
    path('formtypedelete/<str:title>/<pk>/', FormTypeModelDelete.as_view(), name="form_type_delete"),
]

urlpatterns = [
    path('', include(student_admission_urlpatterns)),
    path('staff/', include(staff_urlpatterns)),
]

sponsor/urls.py
from django.urls import path

from .views import (
    StudentSponsorCreateView,
    StaffSponsorCreateView,
)

app_name = 'Sponsor'
urlpatterns = [
    path('student/admission/', StudentSponsorCreateView.as_view(), name='student_admission'),
    path('staff/create/<str:index_number>/', StaffSponsorCreateView.as_view(), name='staff_create'),
]

student/urls.py
from django.urls import path, include

from .views import (
    StudentAdmissionRedirectView,
    StudentProgrammeSelectionView,
    AdmissionCertificateExaminationView,
    StudentPreviousEducationChangeView,
    StudentAdmissionDetails,
    StaffStudentTemplateView,
    StaffRegisterStudentDetailView,
    StaffStudentCreateView,
    StaffStudentUpdateIndexNumProgrammeUpdateView,
    NewlyAdmittedStudentListView,
    StaffSelectStudentProgramme,
    StaffAllStudentListView,
    StudentGroupByDepartment,
    StaffAddPreviousEducation,
    StaffAddStudentForms,
    StaffStudentDetailView,
    StudentHomePage,
    AccountOverviewPage,
    AccountsChangePasswordPage,
    AccountsReportsPage,
    AccountsProfilePage,
    AccountsAcademicYearSemester,
    AccountsPermissions,
    AutoLevelNewAdmitted,
)

app_name = 'Student'

staff_urlpatterns = [
    path('autolevel100newstudent/', AutoLevelNewAdmitted.as_view(), name='level100NewStudent'),
    path('', StaffStudentTemplateView.as_view(), name='staff_home'),
    path('add/', StaffStudentCreateView.as_view(), name='staff_register'),
    path('changeindexnumberandprogramme/<str:index_number>/', StaffStudentUpdateIndexNumProgrammeUpdateView.as_view(),
         name='staff_change_indexPrg'),
    path('add/continuous/<str:index_number>/', StaffRegisterStudentDetailView.as_view(), name='staff_register_student'),
    path('add/certificate/<str:index_number>/', AdmissionCertificateExaminationView.as_view(), name='staff_add_cert'),
    path('newly/admitted/<slug:programme_slug>/', NewlyAdmittedStudentListView.as_view(), name='staff_newly_admitted'),
    path('newly/admitted/', NewlyAdmittedStudentListView.as_view(), name='staff_newly_admitted_search'),
    path('selectgroupbyprogramme/newlyadmitted', StaffSelectStudentProgramme.as_view(), name='staff_select_student_programme'),
    path('all/', StaffAllStudentListView.as_view(), name='staff_all'),
    path('alldepartment/<slug:department_slug>/', StaffAllStudentListView.as_view(), name='staff_department_all'),
    path('allprogramme/<slug:programme_slug>/', StaffAllStudentListView.as_view(), name='staff_programme_all'),
    path('group/department/', StudentGroupByDepartment.as_view(), name='department_group'),
    path('programmechoices/<str:index_number>/', StudentProgrammeSelectionView.as_view(), name='staff_add_programmes_choices'),
    path('addpreviuoseducation/<str:index_number>/', StaffAddPreviousEducation.as_view(), name='staff_add_previouseducation'),
    path('addadmissionform/<str:index_number>/', StaffAddStudentForms.as_view(), name='staff_add_admissionform'),
    path('detail/<int:pk>/<str:profile__identity>/', StaffStudentDetailView.as_view(), name='staff_student_detail'),
]

accounts_urlpatterns = [
    path('overview/', AccountOverviewPage.as_view(), name='acc_overview'),
    path('updates/', AccountsChangePasswordPage.as_view(), name='acc_updates'),
    path('reports/', AccountsReportsPage.as_view(), name='acc_reports'),
    path('profile/', AccountsProfilePage.as_view(), name='acc_profile'),
    path('semesteracademicyear/', AccountsAcademicYearSemester.as_view(), name='acc_semesterAcademicYear'),
    path('permissions/', AccountsPermissions.as_view(), name='acc_permission'),

]

urlpatterns = [
    path('staff/', include(staff_urlpatterns)),
    path('admissionredirect/<str:serial_number>', StudentAdmissionRedirectView.as_view(),
         name='admission-redirect'),
    path('programmechoices/', StudentProgrammeSelectionView.as_view(), name='programmes_choices'),
    path('admissioncertificateexamsrecords/', AdmissionCertificateExaminationView.as_view(), name='admission_cert_exam_records'),
    path('studentpreviouseducation/', StudentPreviousEducationChangeView.as_view(), name='admission_previous_education'),
    path('admission/details/', StudentAdmissionDetails.as_view(), name='admission_detail'),
    path('home/', StudentHomePage.as_view(), name='home'),
    path('accounts/', include(accounts_urlpatterns)),
]

admission/models.py
from django.db import models
from django.db.models import UniqueConstraint
from phonenumber_field.modelfields import PhoneNumberField
from CollegeManagementSystem.validation import validate_alphanumberic_space
from django.shortcuts import reverse


from INSTITUTION.utils import AcademicYear


class FormTypeManager(models.Manager):
    def get_for_form_batch_creation(self):
        return self.all()

    def search(self, value):
        if value:
            return self.filter(
                models.Q(title__icontains=value) | models.Q(subtitle__icontains=value)
            )
        return self.all()


class FormTypeChoicesModel(models.Model):
    title = models.CharField(max_length=120, validators=[validate_alphanumberic_space])
    subtitle = models.CharField(max_length=120, validators=[validate_alphanumberic_space])
    timestamp = models.DateTimeField(auto_now_add=True)
    objects = FormTypeManager()

    class Meta:
        ordering = ('title', 'id')
        constraints = [
            UniqueConstraint(fields=['title', 'subtitle'], name='unique_formtype')
                       ]

    def get_absolute_url(self):
        return reverse('Admission:form_type_detail',
                       kwargs={
                           'title': self.title,
                           'id': self.id
                       })

    def get_absolute_update_url(self):
        return reverse('Admission:form_type_update',
                       kwargs={
                           'title': self.title,
                           'id': self.id
                       })

    def forms_referenced(self):
        return self.forms

    def __str__(self):
        return self.title + ' (%s)' % self.subtitle


class FormStatusChoice(models.TextChoices):
    COMPLETED = 'completed', 'Completed'
    SUBMITTED = 'submitted', 'Submitted'
    AT_PROFILE = 'at profile', 'At Profile'
    AT_ADDRESS = 'at address', 'At Address'
    AT_CERTIFICATION = 'at certification', 'At Certification'
    AT_EMPLOYMENT = 'at employment', 'At Employment History',
    AT_SPONSOR = 'at sponsor', 'AT SPONSORSHIP'
    AT_PROGRAMME = 'at programme', 'AT PROGRAMME'
    AT_EDUCATION = 'at education', 'AT EDUCATION'
    EXPIRED = 'expired', 'Expired'
    NEW = 'new', 'New'
    PROCESSING = 'processing', 'Processing'
    ACCEPTED = 'accepted', 'Accepted'
    REJECTED = 'rejected', 'Rejected'


class StudentFormsManager(models.Manager):
    def search(self, query, status=None):
        return self.filter(
            models.Q(serial_number__icontains=query or '') & models.Q(status__icontains=status or '')
        )


class StudentForms(models.Model):
    serial_number = models.CharField(max_length=120, unique=True)
    pin_code = models.CharField(max_length=120)
    form_type = models.ForeignKey(max_length=60, to=FormTypeChoicesModel, on_delete=models.CASCADE,
                                  related_name='forms')
    cost = models.IntegerField(null=True, blank=True, help_text='Current in Ghana Cedis')
    candidate_name = models.CharField(max_length=120, null=True, validators=(validate_alphanumberic_space,), blank=True)
    candidate_phone_number = PhoneNumberField(null=True, blank=True)
    sales_point = models.CharField(max_length=120, null=True, blank=True)
    sales_point_location = models.CharField(max_length=120, help_text='Town, city or community', null=True, blank=True)
    sales_agent = models.CharField(max_length=120, verbose_name='Sales agent\'s', null=True, blank=True)
    academic_year = models.CharField(max_length=10, help_text='this_year / next_year', null=True,
                                     choices=AcademicYear.choices(),
                                     default=AcademicYear.default(),
                                     blank=True
                                     )
    timestamp = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=30, choices=FormStatusChoice.choices, default=FormStatusChoice.NEW, null=True)
    is_current = models.BooleanField(default=True, help_text='Current status of the form.')
    objects = StudentFormsManager()

    class Meta:
        verbose_name_plural = 'Student Forms'
        permissions = [
            ('can_audit_admission_form', 'can audit student admission form'),
            ('can_reject_studentform', 'can reject student admission form'),
            ('can_accept_studentform', 'can accept student admission form'),
            ('view_studentform_detail', 'view student admission form detail'),
            ('view_own_forms', 'Can student view their own admission form detail'),
        ]

    def __str__(self):
        return 'Admission forms(%s)' % str(self.serial_number)

    @property
    def student(self):
        return self.student_admission_form

    @property
    def is_locked(self):
        return self.status in (FormStatusChoice.ACCEPTED, FormStatusChoice.REJECTED)

    @property
    def is_admitted(self):
        return self.status == FormStatusChoice.ACCEPTED

    @property
    def has_submitted(self):
        return self.status in (FormStatusChoice.SUBMITTED, FormStatusChoice.ACCEPTED)

    @property
    def can_edit(self):
        return not (self.has_submitted or self.is_locked)

    def get_absolute_url(self):
        return reverse('Admission:detail', kwargs={
            'serial_number': self.serial_number,
        })

    def get_absolute_update_url(self):
        return reverse('Admission:change', kwargs={
            'serial_number': self.serial_number,
            'id':self.id,
        })

    def get_absolute_student_form_url(self):
        return reverse('Admission:form_details',
                       kwargs={
                           'serial_number': self.serial_number,
                           'id':self.id
                       })


def auto_set_forms_status(instance, created, **kwargs):
    if created:
        instance.status = FormStatusChoice.NEW
        instance.save()


models.signals.post_save.connect(auto_set_forms_status, sender=StudentForms)


class SalesOfAdmissionForms(models.Model):
    identity = models.CharField(null=True, blank=True, help_text='ID.', max_length=120)
    admission_form = models.OneToOneField(StudentForms, on_delete=models.CASCADE, related_name='admission_form')
    received_from = models.CharField(max_length=120, help_text='payer\'s name')
    amount = models.FloatField(help_text='amount paying')
    the_sum_of = models.TextField(help_text='amount in words')
    timestamp = models.DateTimeField(auto_now_add=True)
    signature = models.CharField(max_length=120)

    def __str__(self):
        return 'Sale of Admission forms ID:' + self.identity or self.id

    class Meta:
        verbose_name_plural = 'Sales of Admission Forms'


# todo create grade and their value model

templates/base/admission/admission_base.html
{% load static %}
{% load institution_extra %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}
    {% if title %}
        -
    {% endif %}
        {% institutionFullName %}
    </title>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'bootstrap5/css/bootstrap.min.css' %}">
    {% block header %}

    {% endblock %}
</head>
<body>
    {% include 'base/admission/navbar.html' %}
    {% block container %}

    {% endblock %}
    <script src="{% static 'fontawesome5.1/js/all.min.js' %}"></script>
    <script src="{% static 'bootstrap5/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'javaScripts/btn/loading.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

templates/base/admission/navbar.html
{% load institution_extra %}
{% url 'Home:landing_page' as home %}
{% url 'Admission:main_template_page' as admission %}
{% load static %}

<div class="d-print-none container rounded mt-2 d-flex flex-column flex-md-row bg-light shadow-sm justify-content-between  py-1 align-items-center sticky-md-top" >
        <a title="{% institutionFullName %}" class="navbar-brand {% if request.path == home %} active {% endif %}" href="{{ home }}"><img src="{% static 'favicon.png' %}" alt="" width="46" height="46" > {% institutionShortName %}</a>
        <h4 class="text-muted">{{ subtitle|upper }}</h4>

        {% include 'base/admission/userMiniMenu.html' %}
</div>

templates/base/admission/student_admission_form.html
{% load institution_extra %}
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}
    {% if title %}
        -
    {% endif %}
        {% institutionFullName %}
    </title>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'bootstrap5/css/bootstrap.min.css' %}">
    {% block header %}

    {% endblock %}
</head>
<body>
    {% include 'base/admission/navbar.html' %}
    <div class="{% block container_css_class %} container {% endblock %}">
        <div class="row my-3">
            <div class="col-auto mx-auto text-center">
                <h4>Admission Form</h4>
            </div>
        </div>
        <div class="row my-3">
            <div class="col-md-auto mx-auto " >
                <div class="card card_rounded border-0 shadow-sm"  style="overflow-x: auto;">
                    <div class="p-2 d-flex align-items-center justify-content-center gap-2 w-100">
                        <a href="{% if 1 in steps %}{% url 'Accounts:admission_student_profile' serial_number=serial_number %} {% endif %}" class="btn {% if step == 1 %} btn-primary {% elif step %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace">Profile</span>
                        </a>
                        <a href="{% if 2 in steps %}{% url 'Address:admission_student_create' %}{% endif %}" class="p-2 btn {% if step == 2 %} btn-primary {% elif 2 in steps %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace ">Address</span>
                        </a>
                        <a href="{% if 3 in steps %}{% url 'EmploymentHistory:student_admission_create_history' %}{% endif %}" class="p-2 btn {% if step == 3 %} btn-primary {% elif 3 in steps %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace ">Employment</span>
                        </a>
                        <a href="{% if 4 in steps %}{% url 'Sponsor:student_admission' %}{% endif %}" class="p-2 btn {% if step == 4 %} btn-primary {% elif 4 in steps %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace ">Sponsor</span>
                        </a>
                        <a href="{% if 5 in steps %}{% url 'Student:programmes_choices' %}{% endif %}" class="p-2 btn {% if step == 5 %} btn-primary {% elif 5 in steps %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace ">Programme</span>
                        </a>
                        <a href="{% if 6 in steps %}{% url 'Student:admission_cert_exam_records' %}{% endif %}" class="p-2 btn {% if step == 6 %} btn-primary {% elif 6 in steps %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace ">Certificate</span>
                        </a>
                        <a href="{% if 7 in steps %}{% url 'Student:admission_previous_education' %}{% endif %}" class="p-2 btn {% if step == 7 %} btn-primary {% elif 7 in steps %} alert-success {% else %} alert-secondary {% endif %} rounded-pill">
                            <span class="font-monospace ">Education</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row my-3 my-md-5">
            <div class="{% block col_css_class %} col-md-auto  {% endblock col_css_class %} mx-auto ">
                <legend>{{ subtitle }}</legend>
                <hr>
                {% block form_render %}
                    {% crispy form %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script src="{% static 'fontawesome5.1/js/all.min.js' %}"></script>
    <script src="{% static 'bootstrap5/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'javaScripts/btn/loading.js' %}"></script>
{% block scripts %}

{% endblock %}
</body>
</html>

templates/base/admission/userMiniMenu.html
{% load static %}
{% static 'favicon.png' as default_img %}
{% with user=request.user  %}
  <div class="d-flex flex-column align-items-center">
      <div class="dropdown">
          <button class="dropdown-toggle btn p-0 m-0 dropdown-menu-start" id="dropdownStudent" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{{ user.picture.url|default:default_img }}" alt="" srcset="" height="40" width="40" class="img-fluid rounded"> {{ user.get_short_name|title }}</button>
          <ul class="dropdown-menu" aria-labelledby="dropdownStudent">
              <li><a class="dropdown-item" href="#">Dean of Students</a></li>
              <li><a class="dropdown-item" href="#">Your university</a></li>
              <li class="dropdown-divider"></li>
              {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="{% url 'Student:admission-redirect' serial_number=user.identity %}">Admission Form</a></li>
              {% endif %}
              <li><a class="dropdown-item" href="#">Check Admission Status</a></li>
              <li><a class="dropdown-item" href="#">2021 / 2022 Admission Requirement</a></li>
              <li class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Fees & Financial Aid</a></li>
              <li><a class="dropdown-item" href="#">How to apply</a></li>
              <li class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'Home:logout' %}">Logout</a></li>
          </ul>
      </div>
  </div>
{% endwith %}