CollegeManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('admission/', include('admission.urls')),
    path('accounts/', include('accounts.urls')),
    path('student/', include('student.urls')),
    path('address/', include('address.urls')),
    path('employmentHistory/', include('empoymentHistory.urls')),
    path('sponsor/', include('sponsor.urls')),
    path('faculty/', include('faculty.urls')),
    path('department/', include('department.urls')),
    path('institution/', include('INSTITUTION.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('system/', include('system.urls')),
    path('course/', include('course.urls')),
    path('lecturer/', include('lecture.urls')),
    path('klassrm/', include('classRoom.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from .views import LandingPage, AboutUsPage, INSTITUTION_NAME, LoginPage, LogoutPage, AdministratorHomePage
from django.urls import path

app_name = 'Home'
urlpatterns = [
    path('', LandingPage.as_view(), name='landing_page'),
    path('about'+INSTITUTION_NAME.get('institution_short_name').lower(), AboutUsPage.as_view(), name="about_institution"),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('administration/', AdministratorHomePage.as_view(), name='admin'),
]

course/urls.py
from django.urls import path, include
from .views import (
    CourseCreationView,
    CourseDetailView,
    StudentCourseListView,
    get_students_other_courses,
    StaffCourseListView,
    StudentCourseDetail,
    LecturerCoursesListView,
    CourseAssignmentCreateView,
    CourseAssigmentUpdateView,
    get_lecturer_short_infor,
    remove_lecturer_from_course_history,
    LecturerCourseDetailView,
    get_course_details,
)

app_name = 'Course'

staff_urlpatterns = [
    path('all/', StaffCourseListView.as_view(), name='staff_all'),
]

course_assignment_urlpatterns = [
    path('toanotherlecturer/<str:course_code>/', CourseAssignmentCreateView.as_view(), name='assign2another'),
    path('updateassigment/<int:courseassignmentpk>/', CourseAssigmentUpdateView.as_view(), name='assign_update'),
    path('getlecturershrtinfo/<slug:user_slug>/<int:assignment_id>/', get_lecturer_short_infor, name='rm_lec_short_info'),
    path('rmelecturer4rmcoursehist/<str:course_code>/<int:course_assignment_id>/', remove_lecturer_from_course_history, name='assignment_rm_lec4rmhist')

]

student_urlpatterns = [
    path('othersc/', get_students_other_courses, name='student_viewmore'),
    path('thissemester/', StudentCourseListView.as_view(), name='student_current'),
    path('details/<course_code>/', StudentCourseDetail.as_view(), name='stu_details'),
]

lecturer_urlpatterns = [
    path('list/', LecturerCoursesListView.as_view(), name='lec_list'),
    path('details/<course_code>/', LecturerCourseDetailView.as_view(), name='lec_detail'),
]
api_urlpatterns = [
    path('<str:course_code>/details/', get_course_details, name='lec_detail_ajax'),
]
urlpatterns = [
    path('staff/', include(api_urlpatterns)),
    path('api/', include(staff_urlpatterns)),
    path('lecturer/', include(lecturer_urlpatterns)),
    path('addnew/', CourseCreationView.as_view(), name='create'),
    path('detail/<str:code>/<int:id>/', CourseDetailView.as_view(), name='detail'),
    path('student/', include(student_urlpatterns)),
    path('courseassignment/', include(course_assignment_urlpatterns)),
]

dashboard/urls.py
from django.urls import path
from .views import (
    AdminDashboardTemplateView,
)


app_name = 'Dashboard'
urlpatterns = [
    path('admin/', AdminDashboardTemplateView.as_view(), name='admin'),
]

faculty/urls.py
from django.urls import path

from .views import (
    FacultyCreationView,
    FacultyListView,
    FacultyDetailView,
    FacultyUpdateView,
    FacultyDeleteView,
)

app_name = 'Faculty'
urlpatterns = [
    path('add/', FacultyCreationView.as_view(), name='create'),
    path('list/', FacultyListView.as_view(), name='list'),
    path('detail/<slug:slug>/', FacultyDetailView.as_view(), name='detail'),
    path('edit/<slug:slug>/', FacultyUpdateView.as_view(), name='change'),
    path('delete/<slug:slug>/', FacultyDeleteView.as_view(), name='delete'),

]

lecture/urls.py
from django.urls import path, include

from .views import (
    StaffLecturerTemplateView,
    AddLecturerView,
    AddLecturerTemplateView,
    LecturerApplicationCreateView,
    LecturerDepartmentAssignment,
    LecturerListView,
    LecturerDashboardView,
    get_my_information_ajax,
)

app_name = 'Lecturer'

my_ajax_urlpatterns = [
    path('information/', get_my_information_ajax, name='get_my_info'),
]

staff_urlpatterns = [
    path('', StaffLecturerTemplateView.as_view(), name='staff_template'),
    path('add/', AddLecturerView.as_view(), name='staff_add'),
    path('addhome/<str:identity>/', AddLecturerTemplateView.as_view(), name='staff_add_template'),
    path('applicationform/<str:identity>/', LecturerApplicationCreateView.as_view(), name='staff_app_change'),
    path('assigndepartment/<str:identity>/', LecturerDepartmentAssignment.as_view(), name='staff_assign_department'),
    path('all/', LecturerListView.as_view(), name='staff_all'),
    path('all/<slug:department_slug>/', LecturerListView.as_view(), name='staff_department_all'),
]

urlpatterns = [
    path('staff/', include(staff_urlpatterns)),
    path('', LecturerDashboardView.as_view(), name='dashboard'),
    path('myrequest/', include(my_ajax_urlpatterns)),
]

system/urls.py
from django.urls import path
from .views import (
    SemesterCreateView,
    SemesterAcademicYearView,
    SemesterUpdateView,
    PermissionGroupListView,
    PermissionGroupCreate,
    PermissionGroupDetails,
    PermissionDetail,
    AddPermissionTemplateView,
    get_permission_ajax,
    AddMemberToPermissionGroup,
    get_group_members_ajax,
    remove_group_member,
    get_group_member_information,
)


app_name = 'System'
urlpatterns = [
    path('semester/new/', SemesterCreateView.as_view(), name='semester_new'),
    path('semester/change/<str:name>/<int:id>/', SemesterUpdateView.as_view(), name='semester_update'),
    path('semesteracademicyear/', SemesterAcademicYearView.as_view(), name='semester_academic_year'),
    path('permissiongroups/', PermissionGroupListView.as_view(), name='permission_group'),
    path('permissiongroup/add/', PermissionGroupCreate.as_view(), name='permission_group_add'),
    path('permissiongroup/<int:pk>/', PermissionGroupDetails.as_view(), name='permission_group_detail'),
    path('permissiondetail/<int:permission_pk>/', PermissionDetail.as_view(), name='permission_detail'),
    path('addpermission2group/<str:group_name>/<int:group_pk>/', AddPermissionTemplateView.as_view(),
         name='add_permission2group'),
    path('ajaxpermissioncall/<int:permission_pk>/', get_permission_ajax, name='get_permission_ajax'),
    path('ajaxgroupmemberscall/<str:group_name>/', get_group_members_ajax, name='get_group_members_ajax'),
    path('removegroupmember/<str:group_name>/<str:member_identity>/', remove_group_member, name='remove_group_member'),
    path('addmenbertogroup/<str:group_name>/<int:group_pk>/',
         AddMemberToPermissionGroup.as_view(), name='add_member2group'),
    path('staffuserinformation/<str:identity>/<str:group_name>/', get_group_member_information, name='get_user_shortInfo'),
]

dashboard/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseForbidden


class AdminDashboardTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/admin/main.html'

    def get_context_data(self, **kwargs):
        ctx = super(AdminDashboardTemplateView, self).get_context_data(**kwargs)
        ctx['title'] = 'Dashboard'
        return ctx

    def get(self, request, *args, **kwargs):
        if request.user.is_staff:
            return super(AdminDashboardTemplateView, self).get(request, *args, **kwargs)
        else:
            return HttpResponseForbidden(b"Out of bounds.".upper())

dashboard/templates/dashboard/admin/main.html
{% extends 'base/admin/base.html' %}
{% load static %}
{% block container %}
    <div class="container">
        <div class="row my-4">
            <div class="col-auto mx-auto">
                <h5>DASHBOARD</h5>
            </div>
        </div>
        <div class="row p-2 my-4 g-3 bg-light-gold text-gold rounded">
            <div class="col-12">
                <span>System Control</span>
                <hr>
            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/regular_file.svg' as forms_src%}
                {% url 'Admission:admins' as admission_url %}
                {% include 'dashboard/link_thumbnail.html' with img_src=forms_src link=admission_url label='Admission Forms' %}
            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% include 'dashboard/link_thumbnail.html' with img_src=forms_src link='' label='Staff Application' %}
            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/mortarboard.svg' as sa_src %}
                {% url 'System:semester_academic_year' as sa_link %}
                {% include 'dashboard/link_thumbnail.html' with img_src=sa_src link=sa_link label='Semester and Academica Year' %}
            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/security_pass.svg' as security_pass_src %}
                {% url 'System:permission_group' as permission_link %}
                {% include 'dashboard/link_thumbnail.html' with img_src=security_pass_src link=permission_link label='Permissions' %}
            </div>

        </div>
        <div class="row p-2 my-4 g-3 bg-light-gold text-gold rounded">
            <div class="col-12 my-3">
                <span>Institution</span>
                <hr>
            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/university_building.svg' as ubuild_src %}
                {% url 'Faculty:list' as faculty_url %}
                {% include 'dashboard/link_thumbnail.html' with img_src=ubuild_src link=faculty_url label='Faculty' %}

            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/shop.svg' as short_src %}
                {% url 'Department:list' as department_url %}
                {% include 'dashboard/link_thumbnail.html' with link=department_url img_src=short_src label='Department' %}
            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/study.svg' as study_src %}
                {% url 'Department:Programme:list' as programme_url %}
                {% include 'dashboard/link_thumbnail.html' with link=programme_url img_src=study_src label='Programme' %}

            </div>
            <div class="col-6 col-md-4 col-lg-3">
                {% static 'icons/blackboard.svg' as blackboard_src %}
                {% url 'Course:staff_all' as course_link %}
                {% include 'dashboard/link_thumbnail.html' with img_src=blackboard_src label='Courses' link=course_link %}
            </div>
        </div>

        <div class="row p-2 my-4 g-3 my-3 bg-light-gold text-gold rounded">
                <div class="col-12">
                    <span>School People</span>
                    <hr>
                </div>
                <div class="col-6 col-md-4 col-lg-3">
                    {% static 'icons/Student_Male.svg' as stu_male %}
                    {% url 'Student:staff_home' as student_url %}
                    {% include 'dashboard/link_thumbnail.html' with img_src=stu_male link=student_url label='Students' %}
                </div>
                <div class="col-6 col-md-4 col-lg-3">
                        {% static 'icons/staff.svg' as staff %}
                        {% include 'dashboard/link_thumbnail.html' with img_src=staff link='' label='Staff' %}
                    </div>
                    <div class="col-6 col-md-4 col-lg-3">
                        {% static 'icons/lecture.svg' as lecture %}
                        {% url 'Lecturer:staff_template' as lecturer_url %}
                        {% include 'dashboard/link_thumbnail.html' with link=lecturer_url img_src=lecture label='Lecturers' %}
                    </div>
                    <div class="col-6 col-md-4 col-lg-3">
                        {% static 'icons/customs_Officer.svg' as custom_officer %}
                        {% include 'dashboard/link_thumbnail.html' with link='' img_src=custom_officer label='Security' %}
                    </div>

            </div>


    </div>
{% endblock %}